#pragma once

#include "stdc++.h"
using namespace std;

//Given two strings s and t which consist of only lowercase letters.
//String t is generated by random shuffling string s and then add one more letter at a random position.
//Find the letter that was added in t.
//https://leetcode.com/problems/find-the-difference/

class FindDifference
{
public:

	FindDifference()
	{
	}

	~FindDifference()
	{
	}

	char findTheDifference(string s, string t)
	{
		unsigned int sum = 0;
		for (unsigned int j = 0; j<t.size(); j++)
		{
			sum += (int)t.at(j);
		}
		for (unsigned int i = 0; i<s.size(); i++)
		{
			sum -= (int)s.at(i);
		}

		return (char)sum;
	}


};

